tabs:
  main:
    display: Main
    sections:
      -
        display: 'Global Settings'
        fields:
          -
            handle: header_logo
            field:
              container: assets
              max_files: 1
              display: 'Header Logo'
              instructions: 'Also used in search-engine structured data.'
              type: assets
          -
            handle: footer_logo
            field:
              container: assets
              max_files: 1
              type: assets
              display: 'Footer Logo'
          -
            handle: page_banner_image
            field:
              container: assets
              folder: images/site
              max_files: 1
              type: assets
              display: 'Default Page Banner Image'
              instructions: 'Background of the title banner on inner pages, posts, products and services. Pages can override it with their own Banner Image.'
          -
            handle: site_name
            field:
              character_limit: 0
              type: text
              display: 'Site Name'
          -
            handle: meta_description
            field:
              type: text
              display: 'Meta Description'
  social:
    display: Social
    sections:
      -
        fields:
          -
            handle: og_image
            field:
              container: assets
              max_files: 1
              display: 'OG Image'
              type: assets
