tabs:
  main:
    display: Main
    sections:
      -
        display: Content
        fields:
          -
            import: global_page_title
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: featured_image
            field:
              container: assets
              max_files: 1
              type: assets
              display: 'Featured Image'
          -
            import: service_content
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: service_type
            field:
              type: terms
              taxonomies:
                - service_type
              display: 'Service Type'
              mode: select
title: Service
